[package]
name = "hello-solana-native"
version = "0.1.0"
edition = "2021"
resolver = "2"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
borsh = "1.6.0"
solana-program = "2.2.1"

[dev-dependencies]
litesvm = "0.6.1"
solana-sdk = "2.2.1"